security:
    encoders:
        Ath\UserBundle\Entity\Utilisateur: sha512

    role_hierarchy:
        ROLE_STUDENT: ROLE_USER
        ROLE_PROFESSOR: ROLE_USER
        ROLE_ADMINISTRATOR: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern: ^/login$
            anonymous: true
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main

            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path:            /
                target_path_parameter:          _target_path
                use_referer:                    false

            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml

    access_control:
        #- { path: ^/admin, roles: ROLE_ADMINISTRATOR }
        #- { path: /note/professor^, roles: ROLE_PROFESSOR, ROLE_ADMINISTRATOR }
        #- { path: /note/student^, roles: ROLE_STUDENT }
