student_registration:
    pattern:  /register/student
    defaults: { _controller: AthUserBundle:RegistrationStudent:register }
    options:
        expose: true

ath_student_del:
    pattern:  /admin/delete/student
    defaults: { _controller: AthUserBundle:ManageStudent:delete }

ath_students_add_class:
    pattern: /admin/etudiants/classe/{id}
    defaults: { _controller: AthUserBundle:ManageStudent:addStudentsInClass }
    requirements:
        id: \d+

professor_registration:
    pattern:  /register/professor
    defaults: { _controller: AthUserBundle:RegistrationProfessor:register }
    options:
        expose: true

ath_professor_del:
    pattern:  /admin/delete/professor
    defaults: { _controller: AthUserBundle:ManageProfessor:delete }

ath_classe_show:
    pattern: /admin/classe
    defaults: { _controller: AthUserBundle:RegistrationClasse:afficher }

ath_classe_add:
    pattern:  /admin/add/classe
    defaults: { _controller: AthUserBundle:RegistrationClasse:register }

ath_classe_edit:
    pattern:  /admin/edit/classe/{id}
    defaults: { _controller: AthUserBundle:RegistrationClasse:edit }
    requirements:
      id: \d+

ath_classe_del:
    pattern:  /admin/delete/classe/{id}
    defaults: { _controller: AthUserBundle:RegistrationClasse:delete }
    requirements:
      id: \d+

administrator_registration:
    pattern:  /register/administrator
    defaults: { _controller: AthUserBundle:RegistrationAdministrator:register }

ath_administration_index:
    pattern: /administration
    defaults: { _controller: AthUserBundle:Administration:index }

ath_administration_users:
    pattern: /administration/users
    defaults: { _controller: AthUserBundle:Administration:users }
